---
language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.8.0"
notifications:
  email: false
